apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: apm-server-hpa
  namespace: elastic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apm-server
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70